### ISSUE TITLE
Best practices for adding Bootstrap versions

### ISSUE THREAD

**Issue by stephenpiscura** [gohugoio/hugo-mod-bootstrap-scss-v4#2]
This is my first attempt at contributing to a GitHub project so please bear with me. I’m following up on [this support issue in the Hugo forum](https://discourse.gohugo.io/t/working-example-of-hugo-modules-and-bootstrap-scss-files/23090/10).

I thought about taking this approach:

For v4.0.0:
```toml
[module]
[[module.imports]]
path="github.com/twbs/bootstrap"
[[module.imports.mounts]]
source = "tree/v4.0.0/scss"
target = "assets/scss/bootstrap"
```
For v4.1.0:
```toml
[module]
[[module.imports]]
path="github.com/twbs/bootstrap"
[[module.imports.mounts]]
source = "tree/v4.1.0/scss"
target = "assets/scss/bootstrap"
```
and so on.

Is that an abuse of how import mounts are meant to work?

Sorry for the rookie questions; i’d love to be helpful here if I can.
